language: php
dist: trusty

php:
 - 7.3

services:
 - mysql

before_install:
 - mysql -e 'CREATE DATABASE nyucidimana_test;'

before_script:
 - composer install --no-interaction
 - cp .env.testing.example .env
 - php artisan migrate
 - php artisan db:seed
 - php artisan key:generate
 - php artisan jwt:secret

script:
 - vendor/bin/phpunit