language: php

php:
 - 7.3

services:
 - mysql

before_install:
 - mysql -e 'CREATE DATABASE nyucidimana_test;'

before_script:
 - composer install
 - cp .env.testing.example .env
 - php artisan key:generate
 - php artisan jwt:secret

script:
 - vendor/bin/phpunit